name: Github Readme Cache
on:
  workflow_dispatch:
  schedule:
    - cron: 0 */4 * * * # Every 4 hours, change it accordingly
jobs:
  download:
    permissions: write-all
    runs-on: ubuntu-latest
    name: Download SVG files
    strategy:
      matrix:
        type: ["stats", "toplangs"]
        include:
          - type: "stats"
            url: "https://github-readme-stats-shoginn.vercel.app/api?username=shoginn&count_private=true&theme=transparent"
          - type: "toplangs"
            url: "https://github-readme-stats-shoginn.vercel.app/top-langs/?username=shoginn&layout=compact&theme=transparent&exclude_repo=Dice-Game-Logic-Proof"
    steps:
      - uses: actions/checkout@v4
      - name: Download SVG file
        uses: suisei-cn/actions-download-file@v1.4.0
        with:
          url: ${{ matrix.url }}
          target: grs
          filename: ${{ matrix.type }}.svg
      - name: Upload SVG file
        uses: actions/upload-artifact@v3.1.3
        with:
          name: ${{ matrix.type }}
          path: grs
  push:
    permissions: write-all
    runs-on: ubuntu-latest
    name: Push SVG Files
    needs: [download]
    steps:
      - uses: actions/download-artifact@master
        with:
          path: grs
      - name: Push
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: resource/grs # May change to your desired branch name, the final URL need to be updated if you change this
          build_dir: grs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
